ros-industrial/noether

.travis.yml
Based on rosindustrial/a5:kinetic docker image which i will provide more documentation on shortly. https://hub.docker.com/r/rosindustrial/a5/
Basically, this image has the following features:
- VTK 7.1
- PCL 1.8 built on VTK 7.1
- ros industrial core
The CI currently fails due to failed tests.
=> add travis CI

vtk_viewer/src/vtk_utils.cpp
The vtk surface intersection routine fails if the face normal is not a unit vector.
=> Normalize face normal in generateNormals

README.md
The previous installation procedures aren't detailed enough and caused me to install the wrong versions of vtk and pcl.  This change adds more detail to help install the right versions of each major source dependency.
=> Improved source dependencies installation procedure

mesh_segmenter/CMakeLists.txt, mesh_segmenter/include/mesh_segmenter/mesh_segmenter.h, mesh_segmenter/package.xml, mesh_segmenter/src/mesh_segmenter.cpp, mesh_segmenter/test/utest.cpp, noether/CMakeLists.txt, noether/launch/mesh_segmenter.launch, noether/package.xml, noether/src/mesh_segmenter_node.cpp, noether/src/segmentation_server.cpp, noether_examples/CMakeLists.txt, noether_examples/include/noether_examples/noether_examples.h, noether_examples/launch/mesh_segmenter_node.launch, noether_examples/launch/mesh_segmenter_server_client.launch, noether_examples/launch/noether.launch, noether_examples/package.xml, noether_examples/src/mesh_segmenter_client.cpp, noether_examples/src/mesh_segmenter_node.cpp, noether_msgs/CMakeLists.txt, noether_msgs/action/Segment.action, noether_msgs/package.xml, vtk_viewer/include/vtk_viewer/vtk_utils.h
- Creates a noether_examples package
- Adds a standalone segmentation node
- Adds a segmentation action server (and client example)
Note:
@Levi-Armstrong suggested changing the normal calculation to MLS for better accuracy. I think this will solve some of the issues with floating holes being left behind in meshes from 3d scans. This could probably be left for another PR.
=> Add segmentation nodes

noether/CMakeLists.txt, noether/package.xml, noether/src/segmentation_server.cpp, noether_examples/CMakeLists.txt, noether_examples/package.xml, tool_path_planner/CMakeLists.txt, tool_path_planner/src/utilities.cpp
These changes add the `pcl_conversions` dependency where necessary and removes it when the needed functions are found in `pcl/conversions.h.`  The [pcl_conversions package only contains a header file](https://github.com/ros-perception/perception_pcl/tree/melodic-devel/pcl_conversions) so it should not cause any  runtime issues as far as I know.
=> Fix the pcl_conversions build issue

path_sequence_planner/test/utest.cpp, tool_path_planner/test/utest.cpp, vtk_viewer/test/utest.cpp
- add #ifdef checking whether build is debug or release to tests
- vtk_viewer
- tool_path_planner
- path_sequence_planner
- If built in debug, visualizations will appear for inspection
- If built in release, visualizations will not appear and the tests will terminate without user intervention.
- this should allow tests to be run by CI
=> Adding Debug Guards to Tests

mesh_segmenter/CMakeLists.txt, mesh_segmenter/test/utest.cpp
A small change to the mesh_segmenter package.  The existing test uses a flag near the top to switch between debug and release 'mode', as some code in the test requires user intervention to complete.  However, this flag was left as true during its last commit.
This PR addresses the issue by replacing the flag with #ifdef NDEBUG guards.  NDEBUG guards cannot accidentally be left 'on' or 'off', so accidental CI-breaking should happen less often.
=> Updated mesh_segmenter test

mesh_segmenter/test/utest.cpp, noether_msgs/msg/ToolPathConfig.msg, tool_path_planner/include/tool_path_planner/raster_tool_path_planner.h, tool_path_planner/include/tool_path_planner/tool_path_planner_base.h, tool_path_planner/src/raster_tool_path_planner.cpp, tool_path_planner/src/utilities.cpp, tool_path_planner/test/utest.cpp, vtk_viewer/include/vtk_viewer/vtk_utils.h, vtk_viewer/src/vtk_utils.cpp
This is a new and improved version of PR #30 
This pull request adds the ability to raster in a direction other than the Major axis (the longest axis of the bounding box). Before, there was cut_direction_ which could be specified, but this was just a vector in world coordinates. The new raster_angle parameters allows you to specify an angle about the vector coming out of the mesh with 0 being in the direction of the principal axis. There is also a flag raster_wrt_principal_axis. When true, the above is true. When false, the idea is that you would specify the angle in world coordinates and then those would be projected onto the surface. This has not yet been implemented.
Run the test to visualize the different types. The first 4 are from this Also, I have commonly had to run the tests more …
=> Rotate raster direction

noether/src/surface_raster_planner_server.cpp, tool_path_planner/include/tool_path_planner/raster_path_generator.h, tool_path_planner/include/tool_path_planner/raster_tool_path_planner.h, tool_path_planner/include/tool_path_planner/tool_path_planner_base.h, tool_path_planner/src/raster_path_generator.cpp, tool_path_planner/src/raster_tool_path_planner.cpp
I had previously added the raster angle to the RasterToolPathPlanner, but since it is already in the ProcessTool that is not needed. As a result, the action interface did not pass the raster angle through. This fixes that.
=> Fix rotate raster in ROS action

noether/src/segmentation_server.cpp, noether_examples/launch/mesh_segmenter_server_client.launch, noether_examples/src/mesh_segmenter_client.cpp, noether_msgs/msg/SegmentationConfig.msg, vtk_viewer/include/vtk_viewer/vtk_utils.h, vtk_viewer/src/vtk_utils.cpp
This PR adds the option to use the normals defined by the triangle of the input mesh defined by the right hand rule. 
Currently for segmentation the normals are calculated by using MLS on the points, then averaging the point normals for each point in a cell to get the cell normals. This has the advantage of not requiring that the mesh have correctly oriented faces, but you can end up with normals that look like this. As you can see, the bottom side of the mesh is inside the MLS radius. Further, the MLS implementation we are using specifies a fixed viewpoint, so the bottom normals are facing up instead of out.
Since in many cases we know the origin of the mesh and can guarantee that it will be clean, we can just use the triangle normals directly. This is also useful in that if it looks …
=> Add methods for calculating normals

noether/config/tool.yaml, noether/src/surface_raster_planner_application.cpp, noether_msgs/msg/ToolPathConfig.msg, tool_path_planner/include/tool_path_planner/raster_tool_path_planner.h, tool_path_planner/include/tool_path_planner/tool_path_planner_base.h, tool_path_planner/src/raster_path_generator.cpp, tool_path_planner/src/raster_tool_path_planner.cpp, tool_path_planner/src/utilities.cpp
When the ability to rotate the raster direction was added in PR 31, there were two parameters added to the ProcessTool struct and the corresponding ToolPathConfig message type.  The first one was the raster angle.  The second one was a flag to switch between rotating about one of the principal axes and rotating about the mesh's coordinate frame axes.  As indicated in the documentation for the ProcessTool struct, the intent was for this flag to default to true (principal axis).  Unfortunately, ROS messages fill booleans with false (coordinate axis) by default.
This caused previously written code using the action server to subtly change without notice.  Some meshes would not be affected, while some would now fail to generate an initial intersection.
This commit refactors the …
=> Refactoring: Making Old Initial-Cut-Generation Behavior the Default

mesh_segmenter/include/mesh_segmenter/mesh_segmenter.h, mesh_segmenter/package.xml, noether/include/noether/surface_raster_planner_application.h, noether/package.xml, noether_conversions/include/noether_conversions/noether_conversions.h, noether_conversions/package.xml, noether_examples/include/noether_examples/noether_examples.h, noether_examples/package.xml, noether_msgs/package.xml, path_sequence_planner/include/path_sequence_planner/path_sequence_planner.h, path_sequence_planner/include/path_sequence_planner/simple_path_sequence_planner.h, path_sequence_planner/package.xml, tool_path_planner/include/tool_path_planner/raster_path_generator.h, tool_path_planner/include/tool_path_planner/raster_tool_path_planner.h, tool_path_planner/include/tool_path_planner/tool_path_planner_base.h, tool_path_planner/include/tool_path_planner/utilities.h, tool_path_planner/package.xml, vtk_viewer/include/vtk_viewer/mouse_interactor.h, vtk_viewer/include/vtk_viewer/vtk_utils.h, vtk_viewer/include/vtk_viewer/vtk_viewer.h, vtk_viewer/package.xml
Noether was intended to be released as Apache 2.0 when it was released as open source. However, the license notices were never updated. This commit updates the notices in the headers as well as the package.xml to correctly state the license as Apache 2.0 rather than proprietary.
Addresses #44 and partially #14
=> Correct License Information to Apache 2.0

noether/src/segmentation_server.cpp, tool_path_planner/src/raster_tool_path_planner.cpp
Changes the PCL verbosity level in order to keep the console from being flooded with non fatal error messages
=> sets the pcl verbosity level to L_ALWAYS to silence unnecessary error messages

README.md
Before they were pointing to PCL 1.8.0 and VTK 7.1.0. While I believe noether should run in its current state regardless, there are some bug fixes in PCL 1.8.1 (and presumably vtk 7.1.1) that are useful to have.
=> Update link in readme to PCL 1.8.1 and VTK 7.1.1

noether_conversions/CMakeLists.txt
PCL was missing and so building against the noether_conversions package would fail
=> Added PCL to the dependency list in the noether_conversions package

noether_filtering/CMakeLists.txt, noether_filtering/README.md, noether_filtering/cloud_filter_plugins.xml, noether_filtering/mesh_filter_plugins.xml, noether_filtering/src/cloud/plugins.cpp, noether_filtering/src/mesh/bspline_reconstruction.cpp, noether_filtering/src/mesh/plugins.cpp
PCL 1.9 and VTK 8.2 are currently only required for the mesh plugins. This PR checks if those versions of the package are available; if not, only the cloud filter plugins are built
Merge after #59
=> Noether Filtering PCL Flexibility

README.md, mesh_segmenter/CMakeLists.txt, mesh_segmenter/include/mesh_segmenter/mesh_segmenter.h, noether/CMakeLists.txt, noether_conversions/CMakeLists.txt, noether_conversions/package.xml, noether_conversions/src/noether_conversions.cpp, noether_examples/CMakeLists.txt, noether_filtering/CMakeLists.txt, path_sequence_planner/CMakeLists.txt, tool_path_planner/CMakeLists.txt, vtk_viewer/CMakeLists.txt
VTK 7.1 is actually available as a debian package starting in Ubuntu 18.04.  Staying on VTK 7.1 would therefore allow some people to use this library without building VTK from source.
I do not believe any new capability from VTK 8.2 is in use, so moving back to VTK 7.1 should not cause any problems.
If I am not mistaken, the motive for moving to VTK 8.2 was to suppress deprecation warnings printed during segmentation.  There is a function in vtkObject that allows the suppression of terminal output.  Calling this function during the construction of a segmentation object would prevent these messages from printing.  (This change has been made.)  It would also be possible to find the exact line that references deprecated code, and wrap it in calls to turn the output off then on.  This way, …
=> Fix/remove need for vtk 8.2

README.md, noether/CMakeLists.txt, noether/config/halfedge_boundary_finder.yaml, noether/launch/halfedge_boundary_finder_server.launch, noether/src/halfedge_boundary_finder_server.cpp, noether_examples/CMakeLists.txt, noether_examples/config/halfedge_finder.rviz, noether_examples/launch/halfedge_finder.launch, noether_examples/launch/halfedge_finder_demo.launch, noether_examples/src/halfedge_finder_node.cpp, tool_path_planner/CMakeLists.txt, tool_path_planner/include/tool_path_planner/half_edge_boundary_finder.h, tool_path_planner/include/tool_path_planner/utilities.h, tool_path_planner/src/edge_path_generator.cpp, tool_path_planner/src/halfedge_boundary_finder.cpp, tool_path_planner/src/utilities.cpp
This PR adds a new capability which computes the edges by collecting the halfedges from the mesh. It's far more robust than the current method which uses covariance computation and requires less tuning.  It needs a mesh without duplicate points.  In a subsequent PR I'll add a simplification filter that removes duplicate points from a mesh but for now this should work as long a proper mesh is passed.  
Run the demo as follows
```
roslaunch noether_examples halfedge_finder_demo.launch
```
=> Feature halfedge boundary finder

README.md
Just a few changes to the readme to clear up some confusion that I and a few other people had with the installation instructions.
- Makes it more clear what --jobs=# is doing on the make steps, and how to get the most out of this option.
- Clarifies that ccmake is an actual command, not a typo
=> Slight edits to clean up installation instructions

noether/config/mesh_filter_manager.yaml, noether_filtering/CMakeLists.txt, noether_filtering/include/noether_filtering/mesh/clean_data.h, noether_filtering/include/noether_filtering/mesh/windowed_sinc_smoothing.h, noether_filtering/mesh_filter_plugins.xml, noether_filtering/src/mesh/clean_data.cpp, noether_filtering/src/mesh/plugins.cpp, noether_filtering/src/mesh/windowed_sinc_smoothing.cpp
This PR adds 2 mesh filter plugins that do the following
- Clean Data: Removes duplicate points and rectifies degenerate artifacts among other things.
- WindowedSincSmoother: Smooths out noisy meshes
The **Simplification** filter group listed in the `noether/config/mesh_filter_manager.yaml` was used
```
roslaunch noether_examples mesh_filtering_demo.launch filter_group:=Simplification
```
Requires PR #73
=> Feature new mesh filters

noether/config/halfedge_boundary_finder.yaml, noether/config/mesh_filter_manager.yaml, noether/src/halfedge_boundary_finder_server.cpp, noether_examples/launch/surf_raster_planner_application.launch, noether_filtering/src/mesh/euclidean_clustering.cpp, tool_path_planner/include/tool_path_planner/half_edge_boundary_finder.h, tool_path_planner/src/halfedge_boundary_finder.cpp
This PR adds the ability to enforce equal spacing between adjacent points in the edge path generated by the halfedge boundary finder
=> Feature edge path equal spacing

vtk_viewer/package.xml
Without this export entry packages that depend on vtk_viewer fail to compile
=> Export cmake build type to fix build error with other packages

noether_conversions/include/noether_conversions/noether_conversions.h
There was a small build error that appeared when linking against noether_conversions.  Using double literals as default values for float parameters caused very messy build errors.  This may be due to the use PCL 1.10 on Ubuntu 20.04 / ROS Noetic by default.
In order to address this error, the double literals had to be changed to float literals in two functions.  It may be a good idea to crawl through the repository making such adjustments (since it should be triggering warnings anyway during compilation and could create similar errors in the future.
=> Use Float Literals to Fix Build Error on Ubuntu 20.04 / ROS Noetic

tool_path_planner/src/plane_slicer_raster_generator.cpp
Breaking out the less controversial content from #116:
The plane slice tool path planner produces incorrect output for a mesh whose centroid is not near its origin. In my test case, the paths are not straight but follow a curved arc. The culprit is the mesh transformation being applied backwards:
https://github.com/ros-industrial/noether/blob/0552f11694f4ee7e3d126d567d1ca81fd35ac01c/tool_path_planner/src/plane_slicer_raster_generator.cpp#L471-L481
=> Bug fix for plane-slice planner

tool_path_planner/include/tool_path_planner/surface_walk_raster_generator.h, tool_path_planner/src/surface_walk_raster_generator.cpp
I encountered the a bug in the surface-walk tool path planner relating to the specification of the `cut_direction` and `cut_centroid` parameters. The size of the `cut_direction` vector is used to create the initial slice through the mesh. If you set this without regard to the size of your mesh, the first plane cutting the mesh may not fully cross the mesh. The result is tool paths that do not span the entire surface. My solution to this issue is to scale the `cut_direction` vector by the size of the largest OBB axis such that the cutting plane is always wide enough to intersect the entire mesh
This PR also removes the `cut_centroid` parameter. This parameter is unused in the rest of the repository and isn't even defined in the `noether_msgs` surface walk planner config message. Retaining …
=> Bug fix for surface-walk tool path planner

noether_msgs/msg/SurfaceWalkRasterGeneratorConfig.msg, tool_path_planner/include/tool_path_planner/surface_walk_raster_generator.h, tool_path_planner/src/surface_walk_raster_generator.cpp, tool_path_planner/src/utilities.cpp, tool_path_planner/test/utest.cpp
The current surface walk tool path planner does not properly implement the specification of raster direction with respect to an axis defined in the coordinate system of the mesh. This PR eliminates the `raster_wrt_global_axes_flag` in favor of utilizing the `cut_direction` parameter. If any element of `cut_direction` is non-zero, it will be used as the raster direction. 
Under the hood, the `cut_direction` vector is projected onto the plane defined by the average normal of the mesh. The projected vector then becomes the raster axis, and the average normal becomes the axis about which the raster axis can be rotated by the specified rotation offset.
Cut Direction = [-1, 1, 0]
Cut direction = [1, 1, 0]
Addresses #110 
Merge after #119
=> Raster w.r.t. a specified direction

noether/src/tool_path_planner_server.cpp
The tool path planner action server currently produces empty tool paths. This is because there is one line missing in the `tool_path_planner_server.cpp` file which copies the local variable (which holds the tool path information) into the action response variable.
I tested this change and it resolved the issue.
=> Fix bug in tool_path_planner_server.cpp

noether_filtering/package.xml
Adds `ros_industrial_cmake_boilerplate` to `noether_filtering` package.xml
=> Update noether_filtering package.xml

noether_tpp/CMakeLists.txt, noether_tpp/include/noether_tpp/tool_path_modifiers/organization_modifiers.h, noether_tpp/src/tool_path_modifiers/organization_modifiers.cpp, noether_tpp/test/tool_path_modifier_utest.cpp
This PR adds tool path modifiers that change the way that tool paths are organized for raster and snake-style tool paths
=> Refactor: tool path organization modifiers

noether_tpp/include/noether_tpp/tool_path_modifiers/organization_modifiers.h, noether_tpp/include/noether_tpp/tool_path_modifiers/waypoint_orientation_modifiers.h, noether_tpp/src/tool_path_modifiers/organization_modifiers.cpp, noether_tpp/src/tool_path_planners/edge_planner.cpp, noether_tpp/src/tool_path_planners/raster_planner.cpp, noether_tpp/test/tool_path_modifier_utest.cpp
This PR:
- Implements the tool path modifiers to produce the standard raster path configuration in the raster planner class
- Adds a tool path modifier for organizing edge path plans into the desired configuration
- Implements the tool path modifiers to produce the standard edge path configuration in the edge planner class
=> Refactor: Tool Path Modifiers for Standard Raster and Edge Path Planner Configuration

noether_gui/include/noether_gui/utils.h
Fixed a small logic error introduced in https://github.com/ros-industrial/noether/pull/169/commits/3770131cbf7d6f52a4e1bffcbb78ee26e3581d1f
=> Fixed logic in GUI exception

noether_filtering/CMakeLists.txt
This PR updates the `noether_filtering` CMakeLists to export its `find_package` dependencies correctly
=> noether_filtering CMakeLists Update

noether_msgs/msg/PlaneSlicerRasterGeneratorConfig.msg, noether_tpp/src/tool_path_planners/plane_slicer_raster_planner.cpp, tool_path_planner/src/utilities.cpp
Fix issue #179 with normals. The changed line was previously changing the normals according to vx, I used something similar to what is used in the waypoint_orientation_modifiers: https://github.com/ros-industrial/noether/blob/e0b5b17c08e545bff471d9878ba43b3bd25ae27b/noether_tpp/src/tool_path_modifiers/waypoint_orientation_modifiers.cpp#L25
=> Fix normals in plane_slicer_raster_planner.cpp

noether_filtering/CMakeLists.txt
Minor update to `noether_filtering` CMakeLists to remove an unnecessary `find_package` on VTK and to fix a couple typos
=> `noether_filtering` CMake Update

noether_gui/CMakeLists.txt, noether_gui/include/noether_gui/widgets/tpp_widget.h, noether_gui/src/tpp_app.cpp, noether_gui/src/widgets/tpp_widget.cpp, noether_gui/ui/tpp_widget.ui
This PR adds a rendering window to the GUI application (inspired by `vtk_viewer`) to improve usability and debug of the planners and GUI components in a stand-alone fashion
https://github.com/ros-industrial/noether/assets/18411310/f2ecfe56-d184-4059-bdcf-b30e993ef795
=> Added viewer to TPP pipeline application

noether_gui/CMakeLists.txt
=> Export dependencies of `noether_gui`

noether_gui/CMakeLists.txt, noether_gui/include/noether_gui/widgets/configurable_tpp_pipeline_widget.h, noether_gui/include/noether_gui/widgets/plugin_loader_widget.h, noether_gui/include/noether_gui/widgets/plugin_loader_widget.hpp, noether_gui/include/noether_gui/widgets/tpp_widget.h, noether_gui/src/tpp_app.cpp, noether_gui/src/widgets/collapsible_area_widget.cpp, noether_gui/src/widgets/configurable_tpp_pipeline_widget.cpp, noether_gui/src/widgets/tpp_pipeline_widget.cpp, noether_gui/src/widgets/tpp_widget.cpp, noether_gui/ui/configurable_tpp_pipeline_widget.ui, noether_gui/ui/plugin_loader_widget.ui, noether_gui/ui/tpp_pipeline_widget.ui, noether_gui/ui/tpp_widget.ui
This PR adds a `ConfigurableTPPPipelineWidget` for use in downstream applications and includes the existing `TPPPipelineWidget` as well as the buttons for loading and saving configurations to YAML file. It also updates the TPP application to use this configurable TPP pipeline widget internally
=> Create Configurable TPP Pipeline Widget

noether_gui/CMakeLists.txt, noether_gui/include/noether_gui/widgets/tool_path_modifiers/concatenate_modifier_widget.h, noether_gui/src/plugins.cpp, noether_gui/src/widgets/tool_path_modifiers/concatenate_modifier_widget.cpp, noether_tpp/CMakeLists.txt, noether_tpp/include/noether_tpp/tool_path_modifiers/concatenate_modifier.h, noether_tpp/src/tool_path_modifiers/concatenate_modifier.cpp
Added toolpath modifier that combines existing toolpaths into a single toolpath.
=> Added Concatenate Toolpath Modifier

noether_gui/include/noether_gui/widgets/tpp_widget.h, noether_gui/src/widgets/tpp_widget.cpp, noether_gui/ui/tpp_widget.ui
1. Compile noether and run the gui
The gui viewer should look like this:
2. Import an object and plan a path with an additional tool path modifier
3. The modified tool path with points and line should be visible
=> Show tool path as polyline

noether_tpp/CMakeLists.txt, noether_tpp/include/noether_tpp/tool_path_planners/multi_tool_path_planner.h, noether_tpp/src/tool_path_planners/multi_tool_path_planner.cpp
This PR adds a tool path planner class that can run multiple tool path planners in a sequence and concatenate their output. This feature supports more complex tool path planning tasks (e.g., cross-hatch rastering) in a modular way
=> Multi tool path planner

noether_gui/include/noether_gui/widgets/tool_path_planners/raster/raster_planner_widget.h, noether_gui/src/widgets/configurable_tpp_pipeline_widget.cpp, noether_gui/src/widgets/tool_path_planners/raster/raster_planner_widget.cpp, noether_gui/src/widgets/tpp_pipeline_widget.cpp, noether_gui/ui/raster_planner_widget.ui, noether_gui/ui/tpp_pipeline_widget.ui, noether_gui/ui/tpp_widget.ui
This PR updates the raster tool path planner widgets to load all origin and direction generator widgets on creation and switch between them using a stacked widget and combo box. It also updates the TPP pipeline widget in a similar way for the tool path planner widgets. This should make it more convenient to switch back and forth between planners without losing the configuration values each time
=> GUI Updates

noether_gui/CMakeLists.txt
Addresses #234, #241 by installing the executable(s) in a location accessible by `ros2 run` and `rosrun`
=> Installed executables for access by ROS

noether_gui/include/noether_gui/widgets/tool_path_planners/raster/plane_slicer_raster_planner_widget.h, noether_gui/src/widgets/tool_path_planners/raster/plane_slicer_raster_planner_widget.cpp, noether_gui/src/widgets/tool_path_planners/raster/raster_planner_widget.ui, noether_tpp/include/noether_tpp/tool_path_planners/raster/plane_slicer_raster_planner.h, noether_tpp/include/noether_tpp/tool_path_planners/raster/raster_planner.h, noether_tpp/src/tool_path_planners/raster/plane_slicer_raster_planner.cpp
The concept of the nominal raster planner is that the user specifies a location where the first raster is made and the direction along which that raster "cuts" the mesh. The direction along which subsequent rasters should step to cover the full surface is left up to the individual planners but is likely to be in a directional orthogonal to the raster "cut" direction and orthogonal to the nominal surface normal.
The plane slicer raster planner calculates the step direction (i.e., cut plane normal) by taking the cross product of the raster "cut" direction with the smallest principal axis of the mesh. Instead of only stepping along this direction (starting at the specified cut origin), the current plane slicer raster planner generates rasters both forward in the direction of the cut plane …
=> Fully support direction generator in plane slicer raster planner 

noether_tpp/src/mesh_modifiers/subset_extraction/extruded_polygon_subset_extractor.cpp
When more than one clusters were being created this would result in a segfault because the comparator actually had to do calculations.
The error I was getting looked like this:
```
[rviz2-1] rviz2: /usr/include/eigen3/Eigen/src/Core/CwiseBinaryOp.h:116: Eigen::CwiseBinaryOp<BinaryOp, Lhs, Rhs>::CwiseBinaryOp(const Lhs&, const Rhs&, const BinaryOp&) [with BinaryOp = Eigen::internal::scalar_difference_op<float, float>; LhsType = const Eigen::Map<Eigen::Matrix<float, -1, -1>, 16, Eigen::OuterStride<> >; RhsType = const Eigen::Replicate<Eigen::Transpose<const Eigen::Matrix<float, 3, 1> >, -1, 1>; Eigen::CwiseBinaryOp<BinaryOp, Lhs, Rhs>::Lhs = Eigen::Map<Eigen::Matrix<float, -1, -1>, 16, Eigen::OuterStride<> >; Eigen::CwiseBinaryOp<BinaryOp, Lhs, Rhs>::Rhs = …
```
=> Fix issue with eigen size mismatch in doing calculation

noether_gui/src/widgets/tool_path_planners/raster/plane_slicer_raster_planner_widget.cpp
Changes per commit message to maintain backwards compatibility with TPP configuration files that may not include the new `bi-directional` parameter
=> Maintain backwards compatibility for TPP config files with bidirectional parameter for plane slice raster planner

noether_tpp/src/tool_path_modifiers/tool_drag_orientation_modifier.cpp
This PR updates the tool drag tool path modifier behavior to *not* offset the tool path by the media radius in the direction of travel as shown in the diagrams below. The current behavior (intended for cutting and grinding applications) does not perform quite as well in practice, even though it puts the edge of the tool radius directly on the input tool path waypoints.
=> Update tool drag tool path modifier behavior

noether_gui/include/noether_gui/widgets/plugin_loader_widget.h, noether_gui/src/widgets/plugin_loader_widget.hpp
Recently I ran into an issue where I created a `noether_gui` plugin in a library outside of this repo, the GUI was able to load it, but then it would segfault when trying to display the widget created by the plugin. It turns out that `boost_plugin_loader` requires plugin objects to remain in scope as long as that plugin (and any object created by it) are being used. When the plugin is destroyed, the library providing its functionality is unloaded.
In the case of the plugin loader widget in this repository, we are currently loading a plugin, creating a widget from it, and then destroying the plugin, which causes the plugin's library to be unloaded. A segfault occurs when trying to access the plugin or objects created by it after the library providing its functionality has been unloaded.
An …
=> Fix plugin loader widget

noether_gui/CMakeLists.txt, noether_gui/include/noether_gui/widgets/mesh_modifiers/normal_estimation_pcl_widget.h, noether_gui/include/noether_gui/widgets/mesh_modifiers/normals_from_mesh_faces_modifier_widget.h, noether_gui/src/plugins.cpp, noether_gui/src/widgets/mesh_modifiers/normal_estimation_pcl_widget.cpp, noether_gui/src/widgets/mesh_modifiers/normals_from_mesh_faces_modifier_widget.cpp, noether_tpp/CMakeLists.txt, noether_tpp/include/noether_tpp/mesh_modifiers/normal_estimation_pcl.h, noether_tpp/include/noether_tpp/mesh_modifiers/normals_from_mesh_faces_modifier.h, noether_tpp/include/noether_tpp/utils.h, noether_tpp/src/mesh_modifiers/normal_estimation_pcl.cpp, noether_tpp/src/mesh_modifiers/normals_from_mesh_faces_modifier.cpp, noether_tpp/src/tool_path_planners/edge/boundary_edge_planner.cpp, noether_tpp/src/tool_path_planners/raster/plane_slicer_raster_planner.cpp, noether_tpp/src/utils.cpp
This PR adds two mesh modifiers that estimate normals for a mesh (one using traditional PCL normal estimation and another that averages face normals for each vertex). After the creation of these modifiers, it is no longer necessary for the plane slice planner to estimate normals within the planner code.
=> Add normal estimation mesh modifiers

noether_gui/CMakeLists.txt, noether_gui/include/noether_gui/widgets/tool_path_modifiers/biased_tool_drag_orientation_modifier_widget.h, noether_gui/src/plugins.cpp, noether_gui/src/widgets/tool_path_modifiers/biased_tool_drag_orientation_modifier_widget.cpp, noether_tpp/CMakeLists.txt, noether_tpp/include/noether_tpp/tool_path_modifiers/biased_tool_drag_orientation_modifier.h, noether_tpp/src/tool_path_modifiers/biased_tool_drag_orientation_modifier.cpp, noether_tpp/test/tool_path_modifier_utest.cpp
- [Added biased tool drag toolpath modifier](https://github.com/ros-industrial/noether/commit/9178880852fa67cc8ae4da3221346e94fe949514)
This PR adds the original tool drag toolpath modifier that was overwritten in #251  
@marip8 can you verify that the toolpath modifier produces the intended behavior? While testing, it seems that for the same region the biased modifier splits the section into two arcs (approaches and departures) while the tool drag modifier only has one arc section.
=> Added biased tool drag toolpath modifier

noether_tpp/src/mesh_modifiers/compound_modifier.cpp
Fixed a bug in the `CompoundModifier` introduced in #283 that causes an infinite loop
=> Fixed bug in compound modifier introduced in #283

noether_gui/src/widgets/tpp_widget.cpp, noether_tpp/src/mesh_modifiers/clean_data_modifier.cpp, noether_tpp/src/mesh_modifiers/fill_holes_modifier.cpp, noether_tpp/src/mesh_modifiers/windowed_sinc_smoothing.cpp, noether_tpp/src/tool_path_planners/raster/plane_slicer_raster_planner.cpp
As mentioned in #292, normals from the input mesh are not preserved when a vtkPolyData object is converted it to a PCL PolygonMesh using pcl::VTKUtils. 
According to [this stale PR on pcl](https://github.com/PointCloudLibrary/pcl/issues/2646), the pcl::io::vtk2mesh retains the normals of the vtkPolyData object when converting it to a PCL PolygonMesh.
This PR uses the vtk2mesh function in pcl::io instead of pcl::VTKUtils to preserve the normals information of the input mesh. This eliminates warnings from the planning pipeline notifying the user that the input mesh does not have normals (even if it does).
=> Using pcl::io instead of pcl::VTKUtils for mesh conversions

noether_gui/include/noether_gui/widgets/tpp_widget.h, noether_gui/src/widgets/tpp_widget.cpp, noether_gui/src/widgets/tpp_widget.ui
- Outputs .ply and .stl files if user adds those file extensions for the modified mesh. If no file extension is specified when saving, the .ply extension is appended to the file
- Added action to file menu and toolbar
- Warning message box appears if user tries to save an empty modified mesh (occurs when no toolpath is generated beforehand)
=> Added feature to save modified mesh

noether_gui/src/widgets/configurable_tpp_pipeline_widget.cpp
When saving a tpp config file, this checks if the file has a .yaml file extension. If it doesn't, ".yaml" is appended to the file name. 
This change allows the QFileDialog to display the save yaml file when loading a tpp configuration. The QFileDialog for loading a tpp config file has the .yaml filter, so files without the .yaml extension would previously not appear in the dialog.
=> Appending .yaml extension to file when saving tpp config

noether_gui/include/noether_gui/widgets/configurable_tpp_pipeline_widget.h, noether_gui/src/widgets/configurable_tpp_pipeline_widget.cpp, noether_gui/src/widgets/tpp_widget.cpp
Per commit title. Exposes default filepaths for QFileDialogs in configurable tpp pipeline widget constructor.
=> Added ability to specify default toolpath config filepath

docs/page_getting_started.dox, noether_gui/include/noether_gui/plugin_interface.h, noether_gui/include/noether_gui/widgets.h, noether_gui/src/plugins.cpp, noether_gui/src/widgets/plugin_loader_widget.hpp
Minor changes to the GUI plugin interface definition to require that the plugin produce a widget that inherits `BaseWidget<T>` rather than a widget that just inherits `QWidget`. The idea is to add clarity to the function of the plugin architecture
=> GUI Interface Update

noether_gui/CMakeLists.txt, noether_gui/include/noether_gui/widgets/angle_double_spin_box.h, noether_gui/include/noether_gui/widgets/distance_double_spin_box.h, noether_gui/src/widgets/angle_double_spin_box.cpp, noether_gui/src/widgets/distance_double_spin_box.cpp, noether_gui/src/widgets/tool_path_modifiers/biased_tool_drag_orientation_modifier_widget.cpp, noether_gui/src/widgets/tool_path_modifiers/circular_lead_in_modifier_widget.cpp, noether_gui/src/widgets/tool_path_modifiers/circular_lead_out_modifier_widget.cpp, noether_gui/src/widgets/tool_path_modifiers/tool_drag_orientation_modifier_widget.cpp, noether_gui/src/widgets/tool_path_planners/raster/cross_hatch_plane_slicer_raster_planner.cpp, noether_gui/src/widgets/tool_path_planners/raster/direction_generators/principal_axis_direction_generator_widget.cpp
Similar to #301, this PR adds a double spin box for angle values that supports degrees and radians units (internally storing the radians value)
=> Angle double spin box

docs/page_getting_started.dox, noether_tpp/CMakeLists.txt
This PR updates the CMakeLists.txt of the noether_tpp library to link against VTK modules that are used by noether_tpp and nother_gui instead of linking against all VTK modules to the nother_tpp target. This prevents an incompatibility issue with some of VTK's modules that are not directly used by noether when linking against noether libraries in other packages. 
For example, when trying to link against noether_tpp in a library that leverages SQLite, the VTK::sqlite module may cause compatibility issues when trying to build your custom library. 
This PR also introduces a cmake-format bash script and github workflow to the repo to maintain a CMakeLists format consistent with the format used by other ros-industrial repos like scan_n_plan_workshop.
=> Update CMakeLists to link against VTK Modules

noether_gui/include/noether_gui/utils.h, noether_gui/src/widgets/configurable_tpp_pipeline_widget.cpp, noether_gui/src/widgets/tpp_pipeline_widget.cpp, noether_gui/src/widgets/tpp_widget.cpp, noether_tpp/include/noether_tpp/utils.h, noether_tpp/src/utils.cpp
This PR moves the printException utility from `noether_gui` to `noether_tpp` for use by downstream projects that interact with the new `noether_tpp` plugins which can throw nested exceptions
=> Move printException utility from noether_gui to noether_tpp

noether_gui/include/noether_gui/widgets/configurable_tpp_pipeline_widget.h, noether_gui/src/tpp_app.cpp, noether_gui/src/widgets/configurable_tpp_pipeline_widget.cpp
This PR updates the configurable TPP pipeline editor widget to store the default file dialog location using a `QSettings` object. After this setting is accessed once in the opening or saving of a file, it's value is set to empty such that subsequent calls to file dialogs will open in the last place the user accessed, rather than always in the default directory.
This PR also adds the file name of the last opened/saved file to the `QSettings` object such that other widgets can know what file this widget opened or saved
=> Configurable TPP Pipeline Widget Update

noether_gui/CMakeLists.txt, noether_gui/include/noether_gui/widgets/mesh_modifiers/cylinder_projection_modifier_widget.h, noether_gui/src/plugins.cpp, noether_gui/src/widgets/mesh_modifiers/cylinder_projection_modifier_widget.cpp, noether_gui/src/widgets/mesh_modifiers/cylinder_projection_modifier_widget.ui, noether_tpp/CMakeLists.txt, noether_tpp/include/noether_tpp/mesh_modifiers/cylinder_projection_modifier.h, noether_tpp/src/mesh_modifiers/cylinder_projection_modifier.cpp, noether_tpp/src/plugins.cpp
This PR adds a cylinder projection mesh modifier, ported from the [`noether_roscon_2024` workshop repository](https://github.com/marip8/noether_roscon_2024/tree/7212e336c7cfb8e9635665946e14861591153e21/src/solution/exercise_2b)
=> Cylinder projection mesh modifier
