noether/config/tool.yaml
noether/src/noether.cpp
tool_path_planner/include/tool_path_planner/raster_tool_path_planner.h
tool_path_planner/include/tool_path_planner/tool_path_planner.h
tool_path_planner/src/raster_tool_path_planner.cpp

This PR adds two things:
1. The option to set the initial cutting direction via a parameter
2. The ability to filter out small segments found during the intersection test (also set via ROS parameter)
@AustinDeric, I rebased off of the master so hopefully Travis will work.

Cutting plane

---

tool_path_planner/include/tool_path_planner/raster_path_generator.h
tool_path_planner/src/raster_path_generator.cpp
tool_path_planner/src/raster_tool_path_planner.cpp

Added a new function that processes multiple meshes in a single call

Raster multiple meshes

---

mesh_segmenter/CMakeLists.txt
mesh_segmenter/package.xml
noether/CMakeLists.txt
noether/package.xml
noether_conversions/CMakeLists.txt
noether_conversions/package.xml
noether_examples/CMakeLists.txt
noether_examples/package.xml
noether_msgs/CMakeLists.txt
path_sequence_planner/CMakeLists.txt
path_sequence_planner/package.xml
tool_path_planner/CMakeLists.txt
tool_path_planner/package.xml
vtk_viewer/CMakeLists.txt
vtk_viewer/package.xml

Changes to the various CMakeLists.txt and package.xml files.  Allows dependent projects to build using "catkin config --install" and still include files from Noether.

Fix Build Issues

---

tool_path_planner/src/raster_path_generator.cpp

As per subject.
For https://github.com/ros-industrial/noether/issues/36.

Include header for std::accumulate(..).

---

noether_filtering/cloud_filter_plugins.xml
noether_filtering/include/noether_filtering/cloud/cloud_filter_manager.h
noether_filtering/include/noether_filtering/cloud/crop_box_filter.h
noether_filtering/include/noether_filtering/cloud/impl/crop_box_filter.hpp
noether_filtering/include/noether_filtering/cloud/impl/pass_through_filter.hpp
noether_filtering/include/noether_filtering/cloud/impl/radius_outlier_filter.hpp
noether_filtering/include/noether_filtering/cloud/impl/statistical_outlier_filter.hpp
noether_filtering/include/noether_filtering/cloud/impl/voxel_grid_filter.hpp
noether_filtering/include/noether_filtering/cloud/pass_through_filter.h
noether_filtering/include/noether_filtering/cloud/radius_outlier_filter.h
noether_filtering/include/noether_filtering/cloud/statistical_outlier_filter.h
noether_filtering/include/noether_filtering/cloud/voxel_grid_filter.h
noether_filtering/include/noether_filtering/impl/filter_group.hpp
noether_filtering/package.xml
noether_filtering/src/filter_group.cpp
noether_filtering/src/filter_manager.cpp
noether_filtering/src/plugins.cpp
noether_filtering/src/test/cloud_utest.cpp

Updates to `noether_filtering` package from #57 for point cloud filter plugins

Cloud Filter Plugins

---

noether/config/mesh_filter_manager.yaml
noether/src/mesh_filter_server.cpp
noether_examples/config/mesh_filtering.rviz
noether_examples/src/mesh_filtering_client.cpp
noether_filtering/include/noether_filtering/filter_group.h
noether_filtering/include/noether_filtering/impl/filter_group.hpp
noether_filtering/include/noether_filtering/mesh/bspline_reconstruction.h
noether_filtering/src/mesh/bspline_reconstruction.cpp

Adds a new parameter and modified the current parameter values to allow converging faster
@marip8  please review

improved mesh filtering demo parameters

---

noether_filtering/cloud_filter_plugins.xml
noether_filtering/include/noether_filtering/cloud/impl/mls_smoothing_filter.hpp
noether_filtering/include/noether_filtering/cloud/mls_smoothing_filter.h
noether_filtering/src/cloud/filters.cpp
noether_filtering/src/plugins.cpp
noether_filtering/src/test/cloud_utest.cpp

Adds MLS smoothing filter for point clouds to `noether_filtering` package. Merge after #58

MLS Smoothing Filter

---

mesh_segmenter/include/mesh_segmenter/mesh_segmenter.h
noether/CMakeLists.txt
noether/config/mesh_filter_manager.yaml
noether/src/mesh_filter_server.cpp
noether_filtering/CMakeLists.txt
noether_filtering/include/noether_filtering/filter_group.h
noether_filtering/include/noether_filtering/impl/filter_group.hpp
noether_filtering/include/noether_filtering/mesh/bspline_reconstruction.h
noether_filtering/src/mesh/bspline_reconstruction.cpp
noether_msgs/action/ApplyMeshFilters.action

Fix crash when skipping boundary curve clipping

---

noether/src/mesh_filter_server.cpp
noether_conversions/include/noether_conversions/noether_conversions.h
noether_conversions/src/noether_conversions.cpp
noether_filtering/include/noether_filtering/impl/filter_manager.hpp
noether_filtering/src/mesh/euclidean_clustering.cpp

Mainly this PR fixes an issue where the filtered meshes were saved with very low floating point precision.

Mesh euclidean clustering improvements

---

mesh_segmenter/include/mesh_segmenter/convex_hull.h
mesh_segmenter/src/convex_hull.cpp
noether/CMakeLists.txt
noether/src/convex_hull_node.cpp
noether_msgs/CMakeLists.txt
noether_msgs/srv/GenerateConvexHull.srv

Refactored & rebased convex hull for noether. ROS interfaces are partitioned into noether/noether, while pure c++ is in mesh_segmenter.

Convex hull

---

README.md
noether/README.md
noether/config/mesh_filter_manager.yaml
noether_examples/launch/surf_raster_planner_demo.launch
noether_filtering/CMakeLists.txt
noether_filtering/README.md
noether_filtering/include/noether_filtering/mesh/fill_holes.h
noether_filtering/mesh_filter_plugins.xml
noether_filtering/src/mesh/fill_holes.cpp
noether_filtering/src/mesh/plugins.cpp

This PR adds a filter for filling holes in meshes, needs PR #77 
@Levi-Armstrong or @drchrislewis please review

Feature mesh hole filler filter

---

README.md

Added instruction about PCL_ENABLE_SSE flag

---

tool_path_planner/src/halfedge_boundary_finder.cpp

This PR addresses #81 by fixing and reinstating the original `applyEqualDistance` method in the half edge boundary finder class

RIGHT FIX of edge 'applyEqualDistance' method

---

mesh_segmenter/package.xml
noether_examples/package.xml
path_sequence_planner/package.xml
tool_path_planner/package.xml
vtk_viewer/package.xml

Addresses #14 to the best of my knowledge. If this information is inaccurate, let me know and I can fix it.

Update maintainer Info

---

README.md

This is to address issue #104 
@gavanderhoorn

Update build instructions in readme

---

noether/launch/tool_path_planner_server.launch
noether_examples/launch/plane_slicer_rastering_generator_demo.launch

Fixes https://github.com/ros-industrial/noether/pull/112#issuecomment-760181615

fix node names

---

README.md
noether_examples/launch/plane_slicer_rastering_generator_demo.launch

Adapted readme for new plane_slicer_rastering_generator_demo.launch file. 
Added default value in plane_slicer_rastering_generator_demo.launch file for mesh file.

Update readme to plane slicer

---

tool_path_planner/src/plane_slicer_raster_generator.cpp
tool_path_planner/test/utest.cpp

This PR corrects the calculation of the cutting plane for the plane slice planner. This was partially addressed in #118, but I don't think I looked at the effect of the rotation offset parameter. I think this issue is not very obvious if the smallest principal axis of the mesh is closely aligned to the Z-axis, but for meshes with arbitrary coordinate frames it becomes a large issue.
The solution implemented in this PR is to use principal component analysis (rather than VTK's objected oriented bounding box method) to get the direction of the cutting and rotation planes. These vectors are then used directly to cut the mesh, rather than transforming the mesh such that it's centroid is at the origin, cutting, then transforming the points back.
- Rasters obviously do not align with mesh …

Fix plane slice planner

---

noether_tpp/CMakeLists.txt
noether_tpp/include/noether_tpp/tool_path_modifiers/waypoint_orientation_modifiers.h
noether_tpp/include/noether_tpp/tool_path_planners/raster/direction_generators.h
noether_tpp/include/noether_tpp/tool_path_planners/raster/origin_generators.h
noether_tpp/src/tool_path_modifiers/waypoint_orientation_modifiers.cpp
noether_tpp/src/tool_path_planners/direction_generators.cpp
noether_tpp/src/tool_path_planners/origin_generators.cpp
noether_tpp/test/tool_path_modifier_utest.cpp

This PR adds various common waypoint orientation modifiers and common raster planner origin/direction generators to the new `noether_tpp` package

Refactor: Modifier and Raster Direction/Origin Generators

---

noether_tpp/include/noether_tpp/core/mesh_modifier.h
noether_tpp/include/noether_tpp/core/tool_path_modifier.h
noether_tpp/include/noether_tpp/core/tool_path_planner.h
noether_tpp/include/noether_tpp/core/tool_path_planner_pipeline.h
noether_tpp/include/noether_tpp/core/types.h
noether_tpp/include/noether_tpp/tool_path_modifiers/compound_modifier.h
noether_tpp/include/noether_tpp/tool_path_planners/raster/origin_generators.h
noether_tpp/include/noether_tpp/tool_path_planners/raster/raster_planner.h
noether_tpp/src/core/tool_path_planner_pipeline.cpp
noether_tpp/src/tool_path_modifiers/compound_modifier.cpp
noether_tpp/src/tool_path_planners/raster_planner.cpp

This PR nests the pointer definition in a typedef in each interface class for easier use

Update pointer definitions

---

noether_tpp/include/noether_tpp/tool_path_modifiers/waypoint_orientation_modifiers.h
noether_tpp/src/tool_path_modifiers/waypoint_orientation_modifiers.cpp
noether_tpp/test/tool_path_modifier_utest.cpp

This PR adds a moving average orientation smoothing tool path modifier

Orientation smoothing

---

noether_tpp/CMakeLists.txt
noether_tpp/include/noether_tpp/mesh_modifiers/compound_modifier.h
noether_tpp/src/mesh_modifiers/compound_modifier.cpp

This PR adds a compound mesh modifier that allows multiple mesh modifiers to be combined in sequence

Compound mesh modifier

---

noether_filtering/CMakeLists.txt
noether_filtering/include/noether_filtering/submesh_extraction/extruded_polygon_mesh_extractor.h
noether_filtering/include/noether_filtering/submesh_extraction/submesh_extractor.h
noether_filtering/src/submesh_extraction/extruded_polygon_submesh_extractor.cpp
noether_filtering/src/submesh_extraction/submesh_extractor.cpp

This PR adds an interface and utility functions for extracting a submesh from a mesh. It also provides an implementation that uses an extruded polygon to extract a submesh

Submesh extraction

---

noether_examples/config/plane_slicer.rviz
noether_examples/launch/plane_slicer_rastering_generator_demo.launch

Add rviz to plane_slicer example

---

noether_tpp/colcon.pkg

Added colcon.pkg file to noether_tpp

---

noether_gui/include/noether_gui/plugin_interface.h
noether_gui/src/plugins.cpp
noether_gui/src/widgets/tpp_pipeline_widget.cpp

Updated inclusion of YAML headers

---

noether_tpp/src/tool_path_planners/raster/plane_slicer_raster_planner.cpp

Previously, when the `mesh` passed to `PlaneSlicerRasterPlanner::planImpl` is coplanar:
- The third element of `scales` is zero.
- Which means that the third column of `pca_vecs` is zero, and so cannot be normalised.
- Which means that `cut_normal` is zero, rather than a unit vector.
This causes the `planImpl` method to return an empty `ToolPaths`, which promptly crashes the modifier it is passed in to.
This PR replaces `pca_vecs.col(2).normalized()`, i.e. `(pca.getEigenVectors().col(2) * scale.z()).normalized()` with `mesh_normal`, i.e. `pca.getEigenVectors().col(2).normalized()`, which should have the same value as before when `scale.z()` is not zero, but which should be a valid unit vector when `scale.z()` is zero.

Fixes plane slicer raster planner planning with coplanar mesh.

---

noether_gui/CMakeLists.txt
noether_gui/include/noether_gui/widgets/tool_path_modifiers/linear_approach_modifier_widget.h
noether_gui/src/plugins.cpp
noether_gui/src/widgets/tool_path_modifiers/linear_approach_modifier_widget.cpp
noether_gui/ui/linear_approach_modifier_widget.ui
noether_gui/ui/vector3d_editor_widget.ui
noether_tpp/CMakeLists.txt
noether_tpp/include/noether_tpp/tool_path_modifiers/linear_approach_modifier.h
noether_tpp/src/tool_path_modifiers/linear_approach_modifier.cpp

Linear approach tool path modifier

---

.github/workflows/clang_format.yml
noether_gui/include/noether_gui/widgets/tool_path_modifiers/linear_approach_modifier_widget.h
noether_gui/src/widgets/tool_path_modifiers/linear_approach_modifier_widget.cpp
noether_tpp/src/tool_path_modifiers/linear_approach_modifier.cpp
noether_tpp/src/tool_path_planners/raster/plane_slicer_raster_planner.cpp

Run clang-format job on 20.04

---

.github/workflows/clang_format.yml
.run-clang-format
noether_filtering/src/mesh/euclidean_clustering.cpp
tool_path_planner/src/surface_walk_raster_generator.cpp

Use clang-format executable

---

noether_gui/CMakeLists.txt
noether_gui/include/noether_gui/widgets/tool_path_modifiers/linear_approach_modifier_widget.h
noether_gui/include/noether_gui/widgets/tool_path_modifiers/linear_departure_modifier_widget.h
noether_gui/src/plugins.cpp
noether_gui/src/widgets/tool_path_modifiers/linear_departure_modifier_widget.cpp
noether_tpp/CMakeLists.txt
noether_tpp/include/noether_tpp/tool_path_modifiers/linear_approach_modifier.h
noether_tpp/include/noether_tpp/tool_path_modifiers/linear_departure_modifier.h
noether_tpp/src/tool_path_modifiers/linear_departure_modifier.cpp

Linear departure tool path modifier

---

noether_tpp/CMakeLists.txt

Adds missing PCL dependency to noether_tpp CMakeLists.txt

---

.github/workflows/ubuntu.yml
dependencies.repos

Updates dependencies where a few issues were resolved, specifically with the plugin loader from [here](https://github.com/tesseract-robotics/boost_plugin_loader/pull/17)

Updated dependencies

---

noether_tpp/src/tool_path_modifiers/linear_approach_modifier.cpp
noether_tpp/src/tool_path_modifiers/linear_departure_modifier.cpp

Bug fix for linear approach/departure modifiers

---

noether_gui/CMakeLists.txt
noether_gui/include/noether_gui/widgets/mesh_modifiers/plane_projection_modifier_widget.h
noether_gui/src/plugins.cpp
noether_gui/src/widgets/mesh_modifiers/plane_projection_modifier_widget.cpp
noether_tpp/CMakeLists.txt
noether_tpp/include/noether_tpp/mesh_modifiers/plane_projection_modifier.h
noether_tpp/src/mesh_modifiers/plane_projection_modifier.cpp

Mesh modifier that fits a plane to the input mesh using RANSAC and projects the inlier points onto the plane

Plane projection mesh modifier

---

noether_tpp/src/tool_path_planners/edge/edge_planner.cpp
noether_tpp/src/tool_path_planners/raster/raster_planner.cpp

Minor edge/raster planner update

---

noether_gui/src/widgets/tpp_widget.cpp

This PR updates the TPP widget to animate the mesh fragments for better visualization of the mesh modifier process

Colorize mesh fragments in visualization

---

noether_gui/CMakeLists.txt
noether_gui/include/noether_gui/widgets/mesh_modifiers/euclidean_clustering_modifier_widget.h
noether_gui/src/plugins.cpp
noether_gui/src/widgets/mesh_modifiers/euclidean_clustering_modifier_widget.cpp
noether_tpp/include/noether_tpp/mesh_modifiers/euclidean_clustering_modifier.h
noether_tpp/src/mesh_modifiers/euclidean_clustering_modifier.cpp

This PR makes some small modifications to the existing Euclidean clustering mesh modifier class and adds a widget plugin for using it in the GUI

Euclidean clustering mesh modifier update

---

noether_gui/include/noether_gui/widgets/mesh_modifiers/plane_projection_modifier_widget.h
noether_gui/src/widgets/mesh_modifiers/plane_projection_modifier_widget.cpp
noether_tpp/include/noether_tpp/mesh_modifiers/plane_projection_modifier.h
noether_tpp/src/mesh_modifiers/plane_projection_modifier.cpp

This PR updates the plane projection mesh modifier to search for and return multiple planes

Plane projection mesh modifier update

---

noether_gui/ui/tpp_widget.ui

Default tool path display update

---

noether_gui/CMakeLists.txt
noether_gui/include/noether_gui/widgets/collapsible_area_widget.h
noether_gui/include/noether_gui/widgets/configurable_tpp_pipeline_widget.h
noether_gui/include/noether_gui/widgets/mesh_modifiers/plane_projection_modifier_widget.h
noether_gui/include/noether_gui/widgets/tool_path_modifiers/circular_lead_in_modifier_widget.h
noether_gui/include/noether_gui/widgets/tool_path_modifiers/circular_lead_out_modifier_widget.h
noether_gui/include/noether_gui/widgets/tool_path_modifiers/concatenate_modifier_widget.h
noether_gui/include/noether_gui/widgets/tool_path_modifiers/direction_of_travel_orientation_modifier_widget.h
noether_gui/include/noether_gui/widgets/tool_path_modifiers/fixed_orientation_modifier_widget.h
noether_gui/include/noether_gui/widgets/tool_path_modifiers/linear_approach_modifier_widget.h
noether_gui/include/noether_gui/widgets/tool_path_modifiers/linear_departure_modifier_widget.h
noether_gui/include/noether_gui/widgets/tool_path_modifiers/moving_average_orientation_smoothing_modifier_widget.h
noether_gui/include/noether_gui/widgets/tool_path_modifiers/offset_modifier_widget.h
noether_gui/include/noether_gui/widgets/tool_path_modifiers/raster_organization_modifier_widget.h
noether_gui/include/noether_gui/widgets/tool_path_modifiers/snake_organization_modifier_widget.h
noether_gui/include/noether_gui/widgets/tool_path_modifiers/standard_edge_paths_organization_modifier_widget.h
noether_gui/include/noether_gui/widgets/tool_path_modifiers/tool_drag_orientation_modifier_widget.h
noether_gui/include/noether_gui/widgets/tool_path_modifiers/uniform_orientation_modifier_widget.h
noether_gui/include/noether_gui/widgets/tool_path_planners/raster/direction_generators/fixed_direction_generator_widget.h
noether_gui/include/noether_gui/widgets/tool_path_planners/raster/direction_generators/principal_axis_direction_generator_widget.h
noether_gui/include/noether_gui/widgets/tool_path_planners/raster/origin_generators/aabb_origin_generator_widget.h
noether_gui/include/noether_gui/widgets/tool_path_planners/raster/origin_generators/centroid_origin_generator_widget.h
noether_gui/include/noether_gui/widgets/tool_path_planners/raster/origin_generators/fixed_origin_generator_widget.h
noether_gui/include/noether_gui/widgets/tool_path_planners/raster/plane_slicer_raster_planner_widget.h
noether_gui/include/noether_gui/widgets/tpp_pipeline_widget.h
noether_gui/include/noether_gui/widgets/tpp_widget.h

Removed unnecessary MOC of widgets

---

noether_gui/include/noether_gui/widgets/plugin_loader_widget.h
noether_gui/include/noether_gui/widgets/plugin_loader_widget.hpp
noether_gui/ui/plugin_loader_widget.ui

https://github.com/ros-industrial/noether/assets/18411310/86fdc5ba-d349-4068-813e-132a11e8e457

Revised plugin loader widget for better usability

---

noether_tpp/include/noether_tpp/mesh_modifiers/compound_modifier.h
noether_tpp/include/noether_tpp/tool_path_modifiers/compound_modifier.h
noether_tpp/include/noether_tpp/tool_path_planners/raster/origin_generators/offset_origin_generator.h

Removed the move/copy constructor/operators from classes that should not be copied or moved

Updated constructors

---

noether_gui/include/noether_gui/widgets/tool_path_planners/raster/plane_slicer_raster_planner_widget.h
noether_gui/src/widgets/tool_path_planners/raster/raster_planner_widget.cpp
noether_gui/src/widgets/tpp_pipeline_widget.cpp
noether_gui/ui/raster_planner_widget.ui
noether_gui/ui/tpp_pipeline_widget.ui
noether_gui/ui/tpp_widget.ui

Various GUI updates per commit messages

Various GUI Updates

---

noether_gui/CMakeLists.txt
noether_gui/include/noether_gui/widgets/tool_path_planners/raster/cross_hatch_plane_slicer_raster_planner_widget.h
noether_gui/src/plugins.cpp
noether_gui/src/widgets/tool_path_planners/raster/cross_hatch_plane_slicer_raster_planner.cpp
noether_tpp/CMakeLists.txt
noether_tpp/include/noether_tpp/tool_path_planners/raster/direction_generators/pca_rotated_direction_generator.h
noether_tpp/src/tool_path_modifiers/snake_organization_modifier.cpp
noether_tpp/src/tool_path_planners/raster/direction_generators/pca_rotated_direction_generator.cpp

This PR adds a cross-hatch raster planner based on the plane slice raster planner

Cross hatch raster planner

---

noether_tpp/CMakeLists.txt
noether_tpp/src/mesh_modifiers/bspline_reconstruction_modifier.cpp

Changes per commit message to address #235

Fix BSpline reconstruction modifier

---

noether_tpp/src/tool_path_planners/raster/plane_slicer_raster_planner.cpp

Changes per commit messages to address #242.
@srsidd can you test to see if this solves the issue you described?

Plane slice raster planner improvements

---

noether_gui/src/widgets/plugin_loader_widget.ui

Updated tool button text in case icon graphics do not exist

---

noether_gui/CMakeLists.txt
noether_gui/include/noether_gui/widgets.h
noether_gui/src/plugin_interface.cpp

Update usage and linking of YAML library

---

noether_tpp/src/tool_path_planners/raster/plane_slicer_raster_planner.cpp

Changes per commit message to reduce unnecessary code duplication. This sort of raster rectification is taken care of [here](https://github.com/ros-industrial/noether/blob/43dde52769873f6ce87f31dd594d2594006de5a9/noether_tpp/src/tool_path_planners/raster/raster_planner.cpp#L23-L26)

Remove duplicate raster rectification in plane slicer raster planner

---

.github/workflows/docker.yml
docker/Dockerfile
docker/docker-compose.override.yml
docker/docker-compose.yml
docker/entrypoint.sh

This PR adds files for building a Docker image of `noether` with an entrypoint that launches the GUI

Add Docker files for GUI application

---

.github/workflows/clang_format.yml
.run-clang-format
noether_gui/src/widgets/tpp_widget.cpp
noether_tpp/src/core/tool_path_planner_pipeline.cpp
noether_tpp/src/mesh_modifiers/compound_modifier.cpp
noether_tpp/src/tool_path_modifiers/compound_modifier.cpp
noether_tpp/src/tool_path_planners/raster/plane_slicer_raster_planner.cpp
noether_tpp/src/utils.cpp

Changes per commit messages to address #280

Fix error reporting around missing vertex normals

---

README.md

Fixed link to documentation in README

---

noether_gui/src/widgets/tpp_widget.cpp
noether_tpp/include/noether_tpp/utils.h
noether_tpp/src/mesh_modifiers/plane_projection_modifier.cpp
noether_tpp/src/utils.cpp

- [Aligning face normals to plane normal in plane projection mesh modifier](https://github.com/ros-industrial/noether/commit/fe8c188ae78f7986f9b867bf5aefe6ab15744141)
- [Added utility function to compute face normals](https://github.com/ros-industrial/noether/commit/5b99d208f324654db6e6d5b01c7a1ac8de2238a8)

Update plane projection modifier

---

.cmake-format
.github/workflows/cmake_format.yml
.run-cmake-format
noether_gui/CMakeLists.txt
noether_tpp/CMakeLists.txt
noether_tpp/test/CMakeLists.txt

Adds a CMake format file, script and CI job

CMake Format

---

docker/docker-compose.yml
docker/entrypoint.sh

Changes per commit message after VTK linking issue resolution in #313

Removed unnecessary LD_LIBRARY_PATH additions for GUI in Docker

---

noether_gui/src/widgets/plugin_loader_widget.cpp

Added checks before widget deletion to prevent warning messages

---

dependencies.repos

Updates to a later version of the CMake boilerplate tool repository

Updated RICB version

---

docs/page_additional_resources.dox
noether_gui/include/noether_gui/plugin_interface.h

GUI Plugin Macro Update and FAQ section in documentation
